{
 "title": "Performance Metrics",
 "tags": [
  "nodejs",
  "api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "Porcentaje de tiempo de CPU utilizado por el proceso de la API.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job='api'}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "timeseries",
   "description": "Tamaño de la memoria residente (RSS) en bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job='api'}"
    }
   ]
  },
  {
   "title": "Node.js Heap Used",
   "type": "timeseries",
   "description": "Memoria utilizada por el heap del motor V8 de JavaScript en bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{job='api'}"
    }
   ]
  },
  {
   "title": "Event Loop Lag (s)",
   "type": "timeseries",
   "description": "Retraso en el event loop de Node.js en segundos.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job='api'}"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "description": "Número total de \"handles\" activos en el event loop.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job='api'}"
    }
   ]
  },
  {
   "title": "Average GC Pause Duration (s)",
   "type": "timeseries",
   "description": "Duración promedio de las pausas del recolector de basura, desglosado por tipo",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_gc_duration_seconds_sum{job='api'}[5m])) by (kind) / sum(rate(nodejs_gc_duration_seconds_count{job='api'}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}